application:
  id: 'reports'

rp:
  jwtExpirationMs: 3600000
  jwtSecret: 792F423F4528482B4D6251655468576D597133743677397A24432646294A404E
 
server:
  port: 6060
  servlet:
    context-path: '/reports'
     
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Shravani12345
    url: jdbc:mysql://localhost:3306/reportsdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
